/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.taller5.view;

import com.mycompany.taller5.controller.LibroControlador;
import com.mycompany.taller5.model.Libro;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nfbar
 */
public class LibroForm extends javax.swing.JFrame {

    LibroControlador libroControlador = new LibroControlador();
    int idLibro;
    /**
     * Creates new form LibroForm
     */
    public LibroForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        libroTable = new javax.swing.JTable();
        tituloText = new javax.swing.JTextField();
        editorialText = new javax.swing.JTextField();
        areaText = new javax.swing.JTextField();
        agregarBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        consultarBoton = new javax.swing.JButton();
        axtualizarBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        libroTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        libroTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libroTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(libroTable);

        agregarBoton.setBackground(new java.awt.Color(51, 255, 51));
        agregarBoton.setText("Agregar");
        agregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBotonActionPerformed(evt);
            }
        });

        jLabel1.setText("Titulo del libro");

        jLabel2.setText("Editorial libro");

        jLabel3.setText("Area libro");

        consultarBoton.setBackground(new java.awt.Color(102, 102, 255));
        consultarBoton.setText("Consultar");
        consultarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBotonActionPerformed(evt);
            }
        });

        axtualizarBoton.setBackground(new java.awt.Color(255, 255, 51));
        axtualizarBoton.setText("Actualizar");
        axtualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axtualizarBotonActionPerformed(evt);
            }
        });

        eliminarBoton.setBackground(new java.awt.Color(255, 0, 0));
        eliminarBoton.setText("Eliminar");
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editorialText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(areaText, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarBoton)
                    .addComponent(axtualizarBoton))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminarBoton)
                    .addComponent(consultarBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editorialText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarBoton)
                    .addComponent(consultarBoton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(axtualizarBoton)
                    .addComponent(eliminarBoton))
                .addGap(0, 50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBotonActionPerformed
        // TODO add your handling code here:
        mostrarTabla();
    }//GEN-LAST:event_consultarBotonActionPerformed

    private void libroTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libroTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) libroTable.getModel();
        int selectRowIndex = libroTable.getSelectedRow();
        idLibro = Integer.parseInt(model.getValueAt(selectRowIndex, 0).toString());
        tituloText.setText(model.getValueAt(selectRowIndex, 1)!= null? model.getValueAt(selectRowIndex, 1).toString():"");
        editorialText.setText(model.getValueAt(selectRowIndex, 2)!= null? model.getValueAt(selectRowIndex, 2).toString():"");
        areaText.setText(model.getValueAt(selectRowIndex, 3)!= null? model.getValueAt(selectRowIndex, 3).toString():"");
        
    }//GEN-LAST:event_libroTableMouseClicked

    private void axtualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axtualizarBotonActionPerformed
        // TODO add your handling code here:
        Libro libro = recogerCampos();
        try {
            libroControlador.actualizarLibro(libro);
            idLibro =0;
            tituloText.setText("");
            editorialText.setText("");
            areaText.setText("");
            mostrarTabla();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "no se puede actualizar el libro");
        }
        
    }//GEN-LAST:event_axtualizarBotonActionPerformed

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        // TODO add your handling code here:
        Libro libro = recogerCampos();
        try {
            libroControlador.eliminarLibro(libro);
            idLibro =0;
            tituloText.setText("");
            editorialText.setText("");
            areaText.setText("");
            mostrarTabla();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "no se puede eliminar el libro");
        }
    }//GEN-LAST:event_eliminarBotonActionPerformed

    private void agregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBotonActionPerformed
        // TODO add your handling code here:
        Libro libro = recogerCampos();
        
        try {
            libroControlador.agregarLibro(libro);
            idLibro = 0;
            tituloText.setText("");
            editorialText.setText("");
            areaText.setText("");
            mostrarTabla();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "no se puede agregar el libro");
        }
    }//GEN-LAST:event_agregarBotonActionPerformed

    public void mostrarTabla(){
        String[] campos = {"IdLibro", "Titulo", "Editorial", "Area"};
        //definir un modelo
        DefaultTableModel modeloDatos = new DefaultTableModel(campos, 0);
        //asignar el modelo a la tabla
        libroTable.setModel(modeloDatos);
        
        ArrayList<Libro> librosBD = libroControlador.consultarLibros();

        for (Libro libro:librosBD){
            Object obejetoDatos [] = {libro.getIdLibro(),libro.getTitulo(), libro.getEditorial(), libro.getArea()};
            modeloDatos.addRow(obejetoDatos);
        }
  
    }
    
    public Libro recogerCampos (){
        Libro libAux =  new Libro(idLibro,tituloText.getText(), editorialText.getText(), areaText.getText());
        
        return libAux;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibroForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBoton;
    private javax.swing.JTextField areaText;
    private javax.swing.JButton axtualizarBoton;
    private javax.swing.JButton consultarBoton;
    private javax.swing.JTextField editorialText;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable libroTable;
    private javax.swing.JTextField tituloText;
    // End of variables declaration//GEN-END:variables
}
