/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reto5prueba.view;

import com.mycompany.reto5prueba.controller.AutorControlador;
import com.mycompany.reto5prueba.controller.LibroControlador;
import com.mycompany.reto5prueba.model.Autor;
import com.mycompany.reto5prueba.model.Libro;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nfbar
 */
public class AutorForm extends javax.swing.JFrame {
    AutorControlador autorControlador = new AutorControlador();
    int idAutor=0;

    /**
     * Creates new form AutorForm
     */
    public AutorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        autorTable = new javax.swing.JTable();
        nombre = new javax.swing.JTextField();
        nacionalidad = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        autorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        autorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(autorTable);

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar)
                    .addComponent(consultar))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete)
                    .addComponent(actualizar)
                    .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregar)
                            .addComponent(actualizar))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consultar)
                            .addComponent(delete))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        mostrarTabla();
    }//GEN-LAST:event_consultarActionPerformed

    private void autorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autorTableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) autorTable.getModel();
        int selectRowIndex = autorTable.getSelectedRow();
        idAutor = Integer.parseInt(model.getValueAt(selectRowIndex, 0).toString());
        nombre.setText(model.getValueAt(selectRowIndex, 1)!= null? model.getValueAt(selectRowIndex, 1).toString(): "");
        nacionalidad.setText(model.getValueAt(selectRowIndex, 2)!= null? model.getValueAt(selectRowIndex, 2).toString(): "");
        
    }//GEN-LAST:event_autorTableMouseClicked

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        Autor autorSave =  recogerCampos();
        autorControlador.createAutor(autorSave);
        idAutor = 0;
        nombre.setText("");
        nacionalidad.setText("");
        mostrarTabla();
    }//GEN-LAST:event_agregarActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        Autor autorSave =  recogerCampos();
        autorControlador.eliminarAutor(autorSave);
        idAutor = 0;
        nombre.setText("");
        nacionalidad.setText("");
        mostrarTabla();
    }//GEN-LAST:event_deleteActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        Autor autorSave =  recogerCampos();
        autorControlador.actualizarAutor(autorSave);
        idAutor = 0;
        nombre.setText("");
        nacionalidad.setText("");;
        mostrarTabla();
    }//GEN-LAST:event_actualizarActionPerformed

    
    private void mostrarTabla() {

        String[] campos = {"IdAutor", "Nombre", "Nacionalidad"};
        
        //definir un modelo
        DefaultTableModel modeloDatos = new DefaultTableModel(campos, 0);
        //asignar el modelo a la tabla
        autorTable.setModel(modeloDatos);
        
        String nombreEntrada = this.nombre.getText();
        String nacionalidadEntrada= this.nacionalidad.getText();
        
        Autor autorEntrada = new Autor(nombreEntrada,nacionalidadEntrada);
        
        
        ArrayList<Autor> autores = autorControlador.consultarAutores(autorEntrada);        //consultar y agregar los datos a la tabla

        for (Autor autor: autores) {
            Integer idAutor = autor.getIdAutor();
            String nombre = autor.getNombre();
            String nacionalidad = autor.getNacionalidad();

            Object objetoDatos[] = {idAutor, nombre, nacionalidad};
            modeloDatos.addRow(objetoDatos);
        } 

    }
    
    public Autor recogerCampos(){
        int idAutor = this.idAutor;
        String nombreEntrada = this.nombre.getText()!= null? this.nombre.getText():"";
        String nacionalidadEntrada = this.nacionalidad.getText()!= null? this.nacionalidad.getText():"";
        
        Autor nuevoAutor = new Autor(idAutor,nombreEntrada,nacionalidadEntrada);
        
        return nuevoAutor;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton agregar;
    private javax.swing.JTable autorTable;
    private javax.swing.JButton consultar;
    private javax.swing.JButton delete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nacionalidad;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
